#include "to_color.h"
#include <map>


using td::ColorID;



td::ColorID to_color(std::string str) {
    for (char& c : str)
        c = std::tolower(c);
    str[0] = std::toupper(str[0]);

    static std::map<std::string, ColorID> string_to_color_map = {
        {"Maroon", ColorID::Maroon},
        {"DarkRed", ColorID::DarkRed},
        {"Brown", ColorID::Brown},
        {"Firebrick", ColorID::Firebrick},
        {"Crimson", ColorID::Crimson},
        {"Red", ColorID::Red},
        {"Tomato", ColorID::Tomato},
        {"Coral", ColorID::Coral},
        {"IndianRed", ColorID::IndianRed},
        {"LightCoral", ColorID::LightCoral},
        {"DarkSalmon", ColorID::DarkSalmon},
        {"Salmon", ColorID::Salmon},
        {"LightSalmon", ColorID::LightSalmon},
        {"OrangeRed", ColorID::OrangeRed},
        {"DarkOrange", ColorID::DarkOrange},
        {"Orange", ColorID::Orange},
        {"Gold", ColorID::Gold},
        {"DarkGoldenRod", ColorID::DarkGoldenRod},
        {"GoldenRod", ColorID::GoldenRod},
        {"PaleGoldenTod", ColorID::PaleGoldenTod},
        {"DarkKhaki", ColorID::DarkKhaki},
        {"Khaki", ColorID::Khaki},
        {"Olive", ColorID::Olive},
        {"Yellow", ColorID::Yellow},
        {"YellowGreen", ColorID::YellowGreen},
        {"DarkOliveGreen", ColorID::DarkOliveGreen},
        {"OliveDrab", ColorID::OliveDrab},
        {"LawnGreen", ColorID::LawnGreen},
        {"Chartreuse", ColorID::Chartreuse},
        {"GreenYellow", ColorID::GreenYellow},
        {"DarkGreen", ColorID::DarkGreen},
        {"Green", ColorID::Green},
        {"ForestGreen", ColorID::ForestGreen},
        {"Lime", ColorID::Lime},
        {"LimeGreen", ColorID::LimeGreen},
        {"LightGreen", ColorID::LightGreen},
        {"PaleGreen", ColorID::PaleGreen},
        {"DarkSeaGreen", ColorID::DarkSeaGreen},
        {"MediumSpringGreen", ColorID::MediumSpringGreen},
        {"SpringGreen", ColorID::SpringGreen},
        {"SeaGreen", ColorID::SeaGreen},
        {"MediumAquaMarine", ColorID::MediumAquaMarine},
        {"MediumSeaGreen", ColorID::MediumSeaGreen},
        {"LightSeaGreen", ColorID::LightSeaGreen},
        {"DarkSlateGray", ColorID::DarkSlateGray},
        {"Teal", ColorID::Teal},
        {"DarkCyan", ColorID::DarkCyan},
        {"Cyan", ColorID::Cyan},
        {"LightCyan", ColorID::LightCyan},
        {"DarkTurquoise", ColorID::DarkTurquoise},
        {"Turquoise", ColorID::Turquoise},
        {"MediumTurquoise", ColorID::MediumTurquoise},
        {"PaleTurquoise", ColorID::PaleTurquoise},
        {"AquaMarine", ColorID::AquaMarine},
        {"PowderBlue", ColorID::PowderBlue},
        {"CadetBlue", ColorID::CadetBlue},
        {"SteelBlue", ColorID::SteelBlue},
        {"CornFlowerBlue", ColorID::CornFlowerBlue},
        {"DeepSkyBlue", ColorID::DeepSkyBlue},
        {"DodgerBlue", ColorID::DodgerBlue},
        {"LightBlue", ColorID::LightBlue},
        {"SkyBlue", ColorID::SkyBlue},
        {"LightSkyBlue", ColorID::LightSkyBlue},
        {"MidnightBlue", ColorID::MidnightBlue},
        {"Navy", ColorID::Navy},
        {"DarkBlue", ColorID::DarkBlue},
        {"MediumBlue", ColorID::MediumBlue},
        {"Blue", ColorID::Blue},
        {"RoyalBlue", ColorID::RoyalBlue},
        {"BlueViolet", ColorID::BlueViolet},
        {"Indigo", ColorID::Indigo},
        {"DarkSlateBlue", ColorID::DarkSlateBlue},
        {"SlateBlue", ColorID::SlateBlue},
        {"MediumSlateBlue", ColorID::MediumSlateBlue},
        {"MediumPurple", ColorID::MediumPurple},
        {"DarkMagenta", ColorID::DarkMagenta},
        {"DarkViolet", ColorID::DarkViolet},
        {"DarkOrchid", ColorID::DarkOrchid},
        {"MediumOrchid", ColorID::MediumOrchid},
        {"Purple", ColorID::Purple},
        {"Thistle", ColorID::Thistle},
        {"Plum", ColorID::Plum},
        {"Violet", ColorID::Violet},
        {"Magenta", ColorID::Magenta},
        {"Orchid", ColorID::Orchid},
        {"MediumVioletRed", ColorID::MediumVioletRed},
        {"PaleVioletRed", ColorID::PaleVioletRed},
        {"DeepPink", ColorID::DeepPink},
        {"HotPink", ColorID::HotPink},
        {"LightPink", ColorID::LightPink},
        {"Pink", ColorID::Pink},
        {"AntiqueWhite", ColorID::AntiqueWhite},
        {"Beige", ColorID::Beige},
        {"Bisque", ColorID::Bisque},
        {"BlanchedAlmond", ColorID::BlanchedAlmond},
        {"Wheat", ColorID::Wheat},
        {"CornSilk", ColorID::CornSilk},
        {"LemonChiffon", ColorID::LemonChiffon},
        {"LightGoldenRodYellow", ColorID::LightGoldenRodYellow},
        {"LightYellow", ColorID::LightYellow},
        {"SaddleBrown", ColorID::SaddleBrown},
        {"Sienna", ColorID::Sienna},
        {"Chocolate", ColorID::Chocolate},
        {"Peru", ColorID::Peru},
        {"SandyBrown", ColorID::SandyBrown},
        {"BurlyWood", ColorID::BurlyWood},
        {"Tan", ColorID::Tan},
        {"RosyBrown", ColorID::RosyBrown},
        {"Moccasin", ColorID::Moccasin},
        {"NavajoWhite", ColorID::NavajoWhite},
        {"PeachPuff", ColorID::PeachPuff},
        {"MistyRose", ColorID::MistyRose},
        {"LavenderBlush", ColorID::LavenderBlush},
        {"Linen", ColorID::Linen},
        {"OldLace", ColorID::OldLace},
        {"PapayaWhip", ColorID::PapayaWhip},
        {"SeaShell", ColorID::SeaShell},
        {"MintCream", ColorID::MintCream},
        {"SlateGray", ColorID::SlateGray},
        {"LightSlateGray", ColorID::LightSlateGray},
        {"LightSteelBlue", ColorID::LightSteelBlue},
        {"Lavender", ColorID::Lavender},
        {"FloralWhite", ColorID::FloralWhite},
        {"AliceBlue", ColorID::AliceBlue},
        {"GhostWhite", ColorID::GhostWhite},
        {"Honeydew", ColorID::Honeydew},
        {"Ivory", ColorID::Ivory},
        {"Azure", ColorID::Azure},
        {"Snow", ColorID::Snow},
        {"Black", ColorID::Black},
        {"DimGray", ColorID::DimGray},
        {"Gray", ColorID::Gray},
        {"DarkGray", ColorID::DarkGray},
        {"Silver", ColorID::Silver},
        {"LightGray", ColorID::LightGray},
        {"Gainsboro", ColorID::Gainsboro},
        {"WhiteSmoke", ColorID::WhiteSmoke},
        {"White", ColorID::White},
        {"SysSelectedItemBackground", ColorID::SysSelectedItemBackground},
        {"SysSelectedTextBackground", ColorID::SysSelectedTextBackground},
        {"SysLabel", ColorID::SysLabel},
        {"SysHeaderText", ColorID::SysHeaderText},
        {"SysHeaderBackground", ColorID::SysHeaderBackground},
        {"SysText", ColorID::SysText},
        {"SysSelectedText", ColorID::SysSelectedText},
        {"SysBackgroundAlternating1", ColorID::SysBackgroundAlternating1},
        {"SysBackgroundAlternating2", ColorID::SysBackgroundAlternating2},
        {"SysTransparentSelection", ColorID::SysTransparentSelection},
        {"SystemDisabledCtrlColor", ColorID::SystemDisabledCtrlColor},
        {"SysControlText", ColorID::SysControlText},
        {"SysLabelHighlight", ColorID::SysLabelHighlight},
        {"SysCtrlBackground", ColorID::SysCtrlBackground},
        {"SysCritical", ColorID::SysCritical},
        {"SysConstructive", ColorID::SysConstructive},
        {"SysDestructive", ColorID::SysDestructive},
        {"Transparent", ColorID::Transparent},
    };

    auto it = string_to_color_map.find(str);
    if (it != string_to_color_map.end()) {
        return it->second;
    }
    else {
        return ColorID::Black;
    }
}